CONSOLE_ENABLE = no
COMMAND_ENABLE = no
AUDIO_ENABLE = no
AUTO_SHIFT_ENABLE = yes
MOUSEKEY_ENABLE = no
ORYX_ENABLE = yes
TAP_DANCE_ENABLE = yes
SPACE_CADET_ENABLE = no
CAPS_WORD_ENABLE = yes
COMBO_ENABLE = yes
SRC += dual_function.c tap_dance.c combos.c rgb.c tapping_term.c process_record.c macros.c caps_word.c
